---
# tasks file for ntp

 - name: include OS specific variables
   include_vars: "{{ ansible_os_family }}.yml"

 - include: Debian.yml
   when: ansible_os_family in ['Debian']

 - include: RedHat.yml
   when: ansible_os_family in ['RedHat']

 - name: copy ntp configuration file
   copy: src=ntp.conf dest=/etc
   notify: restart ntp

 - name: ensure ntp is running
   service: name={{ ntp_service }} state=started enabled=yes

 - name: ensure time zone
   file: src=/usr/share/zoneinfo/{{ time_zone }} dest=/etc/localtime state=link force=yes

